// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderService.Persistence;
using MassTransit; // Added for MassTransit Outbox support

#nullable disable

namespace OrderService.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            // --- MASSTRANSIT INBOX STATE ---
            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                b.Property<DateTime?>("Consumed")
                    .HasColumnType("datetime2");

                b.Property<Guid>("ConsumerId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("Delivered")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("ExpirationTime")
                    .HasColumnType("datetime2");

                b.Property<long?>("LastSequenceNumber")
                    .HasColumnType("bigint");

                b.Property<Guid>("MessageId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("Received")
                    .HasColumnType("datetime2");

                b.Property<int>("ReceiveCount")
                    .HasColumnType("int");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("rowversion");

                b.HasKey("Id");

                b.HasIndex("MessageId", "ConsumerId")
                    .IsUnique();

                b.ToTable("InboxState");
            });

            // --- MASSTRANSIT OUTBOX MESSAGE ---
            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
            {
                b.Property<long>("SequenceNumber")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNumber"), 1L, 1);

                b.Property<string>("Body")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid?>("ConversationId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("CorrelationId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("DestinationAddress")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("FaultAddress")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("Headers")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid?>("InitiatorId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("MessageId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("MessageType")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid?>("OutboxId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Properties")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid?>("RequestId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("ResponseAddress")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<DateTime>("SentTime")
                    .HasColumnType("datetime2");

                b.Property<string>("SourceAddress")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("SequenceNumber");

                b.HasIndex("OutboxId", "SequenceNumber");

                b.HasIndex("SentTime");

                b.ToTable("OutboxMessage");
            });

            // --- MASSTRANSIT OUTBOX STATE ---
            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
            {
                b.Property<Guid>("OutboxId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("Created")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("Delivered")
                    .HasColumnType("datetime2");

                b.Property<long?>("LastSequenceNumber")
                    .HasColumnType("bigint");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("rowversion");

                b.HasKey("OutboxId");

                b.HasIndex("Created");

                b.ToTable("OutboxState");
            });

            // --- ORDER ENTITY ---
            modelBuilder.Entity("OrderService.Entities.Order", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CustomerId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("OrderDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Order", (string)null);
            });

            // --- ORDER ITEM (Owned Entity) ---
            modelBuilder.Entity("OrderService.Entities.Order", b =>
            {
                b.OwnsMany("OrderService.Entities.OrderItem", "Items", b1 =>
                {
                    b1.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                    b1.Property<string>("ArticleTitle") // Fixed Typo here
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b1.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b1.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b1.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b1.Property<int>("Quantity")
                        .HasColumnType("int");

                    b1.HasKey("Id");

                    b1.HasIndex("OrderId");

                    b1.ToTable("OrderItem");

                    b1.WithOwner()
                        .HasForeignKey("OrderId");
                });

                b.Navigation("Items");
            });
#pragma warning restore 612, 618
        }
    }
}